module_order:
  - samtools:
      name: "Samtools (initial)"
      anchor: "samtools_initial"
      info: "This section of the report shows Samtools results after adapter trimming."
      path_filters:
        - "*_samtools_coverage_aligned.txt"
        - "*_samtools_stats_aligned.txt"
  - samtools:
      name: "Samtools (DMS)"
      anchor: "samtools_dms"
      info: "This section of the report shows Samtools results after DMS analysis (codon truncated)."
      path_filters:
        - "*_samtools_coverage_dms.txt"
        - "*_samtools_stats_dms.txt"

extra_fn_clean_exts:
  - "_samtools"